config/routes.rb
Pacedermatology::Application.routes.draw do
  
  get "shop/home"

  match "contact" => "contactus#new"
  match "contact/create" => "contactus#create"

  resources :posts
  

  get "services/medical"
  get "services/surgical"
  get "services/cosmetic"
  get "services/lasers"
  get "services/insurance"
  get "services/nbuvb"
  get "services/hair_removal"
  get "services/ipl"
  get "services/vein_removal"

  get "about/mission"
  get "about/privacy"
  get "about/staff"
  get "about/aaron_pace"
  get "about/andrew_pace"
  get "about/shelly_velickoff"  
  
  get "pages/about"
  get "pages/contact"
  get "pages/art"
  get "pages/services"
  get "pages/contact"

  resources "feeds"
  resources "blogs"
  root to: "pages#home"

end

app/models/author.rb
class Author < ActiveRecord::Base
  attr_accessible :name
  
  validates :name, presence: true, length: {in: 1..255}
end

app/models/contacter.rb
class Contacter
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :name, :email, :content
  
  validates :name, presence: true
  validates :email, email: true
  validates :content, presence: true, length: {maximum: 5000}
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
  
  def send_message
    ::ContactMailer.website(self).deliver
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body, :author_id, :created_at
  
  belongs_to :author
  
  validates :title, presence: true, length: {in: 1..255}
  validates :body, presence: true
  validates :author_id, presence: true
  
  def synopsis
    words = self.body.split(" ")[0..50]
    ::RedCloth.new(words.join(" ") + '...').to_html
  end
  
  def full_body
    ::RedCloth.new(self.body).to_html
  end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def mission; end
  def staff; end
  def aaron_pace; end
  def andrew_pace; end
  def shelly_velickoff; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contactus_controller.rb
class ContactusController < ApplicationController
  def new
    @contacter = Contacter.new
  end
  
  def create
    @contacter = Contacter.new(params[:contacter])
    if @contacter.valid?
      @contacter.send_message
      redirect_to root_path, notice: "Thank you for contacting us.  Your message was successfully sent, and we will be in touch with you as soon as possible."
    else
      render "new"
    end
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
    @contacter = Contacter.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(params[:post])

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_url, notice: 'Post was successfully destroyed'
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def medical; end
  def surgical; end
  def cosmetic; end
  def lasers; end
  def insurance; end
  def hair_removal; end
  def ipl; end
  def vein_removal; end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def home
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/contacters_helper.rb
module ContactersHelper
end

app/helpers/contactus_helper.rb
module ContactusHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/about/associates.html.haml
%h1 About#associates
%p Find me in app/views/about/associates.html.haml

app/views/about/mission.html.haml
%div{class: "row span12"}
  %h3 Our Mission
  %p
    We strive for excellence in patient care and are dedicated to practicing medicine with dignity, compassion, and quality, specifically caring for diseases of the skin, hair and nails.
  %em
    I hope you will join us in meeting our mission.

app/views/about/providers.html.haml
%h1 About#providers
%p Find me in app/views/about/providers.html.haml

app/views/contactus/new.html.haml
%div{class: "row span12"}
  %div
    %h4
      Our Office Numbers:
    %p
      Phone:  #{link_to "(253) 572-2842", "tel: (253) 572-2842"}
      %br
      Fax: (253) 572 2856
  %div
    %h4
      Our Address:
    %address
      Allenmore Medical Office Building B
      %br
      1901 South Union Ave., Suite B3003
      %br
      Tacoma, WA 98405   
  %form{method: "post", action: contact_create_path, class: "form-horizontal"}
    %fieldset
      %legend Send Us a Message
      =render partial: "forms/text", locals: {object: @contacter, method: "name", label: "Your Name"}
      =render partial: "forms/text", locals: {object: @contacter, method: "email", label: "Email"}
      =render partial: "forms/textarea", locals: {object: @contacter, method: "content", label: "Message"}
      %div{class: "control-group"}
        %div{class: "controls"}
          %button{type: "submit", value: "Signup", class: "btn btn-primary"} Send

app/views/forms/_text.html.haml
%div{class: "control-group #{object.errors[method].empty? ? "" : "error"}"}
  %label{for: method, class: "control-label"}
    =label
  %div{class: "controls"}
    %input{type: "text", id: method, value: object.send(method), name: "#{object.class.to_s.downcase}[#{method}]", class: "span4"}
    -unless object.errors[method].empty?
      %span{class: "help-inline"}
        =object.errors[method].to_sentence

app/views/forms/_textarea.html.haml
%div{class: "control-group #{object.errors[method].empty? ? "" : "error"}"}
  %label{for: method, class: "control-label"}
    =label
  %div{class: "controls"}
    %textarea{id: method, name: "#{object.class.to_s.downcase}[#{method}]", class: "span4", rows: "10"}
      =object.send(method)
    -unless object.errors[method].empty?
      %span{class: "help-inline"}
        =object.errors[method].to_sentence

app/views/layouts/_footer.html.haml
%div{class: "row"}
  %div{class: "span2 offset2"}
    %ul{class: "nav nav-list"}
      %li{class: "nav-header"} 
        About
      %li
        %small
          =link_to "Aaron Pace, MD", about_aaron_pace_path, class: "muted"
      %li
        %small
          =link_to "Andrew Pace, MD", about_andrew_pace_path, class: "muted"
      %li
        %small
          =link_to "Shelly Velickoff, ARNP", about_shelly_velickoff_path, class: "muted"
      %li
        %small
          =link_to "Our Staff", about_staff_path, class: "muted"
      %li
        %small
          =link_to "Mission", about_mission_path, class: "muted"
  %div{class: "span2"}
    %ul{class: "nav nav-list"}
      %li{class: "nav-header"} 
        Patients
      %li
        %small
          =link_to "Patient Login", "http://pace.nextechweb.com/patient", class: "muted"
      %li
        %small
          =link_to "New Patient Login", "http://pace.nextechweb.com/patient/newuser", class: "muted"
  %div{class: "span2"}
    %ul{class: "nav nav-list"}
      %li{class: "nav-header"} 
        Legal
      %li
        %small
          =link_to "Privacy Policy", about_privacy_path, class: "muted"
  %div{class: "span2"}
    %ul{class: "nav nav-list"}
      %li{class: "nav-header"} 
        Connect
      %li
        %small
          =link_to "Facebook", "http://facebook.com/pacedermatology", class: "muted"
      %li
        %small
          =link_to "Twitter", "http://twitter.com/akpaceskindoc", class: "muted"
      %li
        %small
          =link_to "YouTube", "http://youtube.com/pacedermatology.com", class: "muted"

%div{class: "row text-center"}
  %p
    %small{class: "muted"}
      Pace Dermatology, PLLC &copy;
%div{class: "row text-center"}
  %p
    =link_to "http://twitter.com/akpaceskindoc" do
      =image_tag "twitter.png"
    =link_to "http://facebook.com/pacedermatology" do
      =image_tag "facebook.png"
    =link_to "http://youtube.com/pacedermatology" do
      =image_tag "youtube.png"
    =link_to feeds_path do
      =image_tag "rss.png"

app/views/layouts/_header.html.haml
%div{class: "row"}
  %p{class: "pull-right"}
    Call us at
    =link_to "(253) 572-2842", "tel:253-572-2842"
    to 
    =link_to "book an appointment", "http://zocdoc.com/practice/pace-dermatology-associates-11032"
    today
%div{class: "row"}
  %p
    =link_to root_path do
      =image_tag "logo.png"
%div{class: "row"}
  %div{class: "navbar navbar-inverse"}
    %div{class: "navbar-inner"}
      %ul{class: "nav"}
        %li
          =link_to "Home", root_path
        %li{class: "dropdown"}
          %a{href: "#", class: "dropdown-toggle", "data-toggle" => "dropdown"}
            About
            %b{class: "caret"}
          %ul{class: "dropdown-menu"}
            %li{class: "dropdown-submenu"}
              =link_to "Our Providers", "#"
              %ul{class: "dropdown-menu"}
                %li
                  =link_to "Dr. Aaron Pace, MD", about_aaron_pace_path
                %li
                  =link_to "Dr. Andrew Pace, MD", about_andrew_pace_path
                %li
                  =link_to "Shelly Velickoff, ARNP", about_shelly_velickoff_path                 
            %li
              =link_to "Our Staff", about_staff_path
            %li
              =link_to "Our Mission", about_mission_path
        %li{class: "dropdown"}
          %a{href: "#", class: "dropdown-toggle", "data-toggle" => "dropdown"}
            Services
            %b{class: "caret"}
          %ul{class: "dropdown-menu"}
            %li
              =link_to "Insurance Coverage", services_insurance_path
            %li
              =link_to "Medical", services_medical_path
            %li
              =link_to "Surgical", services_surgical_path
            %li
              =link_to "Cosmetic", services_cosmetic_path
            %li{class: "dropdown-submenu"}
              =link_to "Lasers", services_lasers_path
              %ul{class: "dropdown-menu"}
                %li
                  =link_to "Laser Hair Removal", services_hair_removal_path
                %li
                  =link_to "IPL Skin Rejuvenation", services_ipl_path
                %li
                  =link_to "Laser Vein Removal", services_vein_removal_path
            %li
              =link_to "Light Therapy", services_nbuvb_path
        %li
          =link_to "Shop", shop_home_path
        %li{class: "dropdown"}
          %a{href: "#", class: "dropdown-toggle", "data-toggle" => "dropdown"}
            Patients
            %b{class: "caret"}
          %ul{class: "dropdown-menu"}
            %li
              =link_to "Current Patient Login", "https://pace.nextechweb.com/patient"
            %li
              =link_to "New Patient Login", "https://pace.nextechweb.com/patient/newuser"
        %li
          =link_to "Resources", posts_path
        %li
          =link_to "Blog", posts_path
        %li
          =link_to "Contact", contact_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Pace Dermatology - #{@page_title || "Come in today"}
    =stylesheet_link_tag "application"
  %body
    %div{class: "container"}
      =render partial: "layouts/header"
      =yield
      =render partial: "layouts/footer"
    =javascript_include_tag "http://code.jquery.com/jquery.js"
    =javascript_include_tag "application"

app/views/pages/about.html.haml
%h1 Pages#about
%p Find me in app/views/pages/about.html.haml

app/views/pages/contact.html.haml
%div{class: "row span12"}
  %div
    %h4
      Our Office Numbers:
    %p
      Phone:  (253) 572-2842
      %br
      Fax: (253) 572 2856

  %div
    %h4
      Our Address:
    %address
      Allenmore Medical Office Building B
      %br
      1901 South Union Ave., Suite B3003
      %br
      Tacoma, WA 98405
      
  %form{method: "post", action: contacters_path, class: "form-horizontal"}
    %fieldset
      %legend Create a blog

      %div{class: "control-group"}
        %label{for: "author_id", class: "control-label"} Author
        %div{class: "controls"}
          =select("blog", "author_id", Author.all.map{|a| [a.name, a.id]}, {}, class: "span4")
      =render partial: "forms/text", locals: {object: @blog, method: "title", label: "Title"}
      =render partial: "forms/textarea", locals: {object: @blog, method: "body", label: "Body"}

      %div{class: "control-group"}
        %div{class: "controls"}
          %button{type: "submit", value: "Signup", class: "btn btn-primary"} Create

app/views/pages/home.html.haml
%div{class: "row"}
  %div{id: "homeCarousel", class: "carousel slide"}
    %ol{class: "carousel-indicators"}
      %li{"data-target" => "#homeCarousel", "data-slide-to" => "0", class: "active"}
      %li{"data-target" => "#homeCarousel", "data-slide-to" => "1"}
      %li{"data-target" => "#homeCarousel", "data-slide-to" => "2"}
    %div{class: "carousel-inner"}
      %div{class: "active item"}
        =image_tag "carousel/aaron.jpg"
        %div{class: "carousel-caption"}
          %h4 Welcome
          %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies
      %div{class: "item"}
        =image_tag "carousel/art.jpg"
        %div{class: "carousel-caption"}
          %h4 Welcome
          %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies          
      %div{class: "item"}
        =image_tag "carousel/art.jpg"
        %div{class: "carousel-caption"}
          %h4 Welcome
          %p Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies        
    =link_to "&lsaquo;".html_safe, "#homeCarousel", class: "carousel-control left", "data-slide" => "prev"
    =link_to "&rsaquo;".html_safe, "#homeCarousel", class: "carousel-control right", "data-slide" => "next"

%div{class: "row"}
  %ul{class: "thumbnails"}

    %li{class: "span4"}
      %h3 Featured Treatment  
      =image_tag "chemical-peel.jpg", class: "img-rounded"
      %h5 Chemical Peels
      %p
        With summer approaching quickly, feel your best with our rejuvenating specials. We’ve taken $100 off the price of our chemical peels to help you take years off. This minimally-invasive procedure helps to correct pigmentary changes and skin laxity, leaving you with refreshed and healthier looking skin.
      =link_to "Learn More &raquo;".html_safe, root_path, class: "btn btn-primary"

    %li{class: "span4"}
      %h3 Featured Product
      =image_tag "eltamd.jpg", class: "img-rounded"
      %h5 EltaMD Sun Care Products
      %p
        We're all hoping for a great Washington summer. No time is more important than now to protect yourself from the sun. Save 15% on these great, broad-spectrum sunscreens.
      =link_to "Learn More &raquo;".html_safe, root_path, class: "btn btn-primary"

    %li{class: "span4"}
      %h3 Featured Laser
      =image_tag "laser.jpg", class: "img-rounded"
      %h5 IPL Rejuvenation
      %p
        Intense Pulsed Light will treat sun spots, photodamage, and redness.  This safe procedure has minimal recovery time and will help reverse years of sun damage and aging.  Schedule today and save $150.
      =link_to "Learn More &raquo;".html_safe, root_path, class: "btn btn-primary"

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%form{method: "post", action: post_path(@post), class: "form-horizontal"}
  %input{type: "hidden", name: "_method", value: "put"}
  %fieldset
    %legend Update a post
    %div{class: "control-group"}
      %label{for: "author_id", class: "control-label"} Author
      %div{class: "controls"}
        =select("post", "author_id", Author.all.map{|a| [a.name, a.id]}, {}, class: "span4")
    =render partial: "forms/text", locals: {object: @post, method: "title", label: "Title"}
    =render partial: "forms/textarea", locals: {object: @post, method: "body", label: "Body"}

    %div{class: "control-group"}
      %div{class: "controls"}
        %button{type: "submit", value: "Signup", class: "btn btn-primary"} Create

app/views/posts/index.html.haml
-@posts.each do |post|
  %div
    %h3
      =post.title
    %span
      =post.created_at.strftime("%B %d, %Y")
      by
    %span
      =post.author.name
    %p
      =post.synopsis.html_safe
    =link_to "Edit", edit_post_path(post)

app/views/posts/new.html.haml
%form{method: "post", action: posts_path, class: "form-horizontal"}
  %fieldset
    %legend Create a post

    %div{class: "control-group"}
      %label{for: "author_id", class: "control-label"} Author
      %div{class: "controls"}
        =select("post", "author_id", Author.all.map{|a| [a.name, a.id]}, {}, class: "span4")
    =render partial: "forms/text", locals: {object: @post, method: "title", label: "Title"}
    =render partial: "forms/textarea", locals: {object: @post, method: "body", label: "Body"}

    %div{class: "control-group"}
      %div{class: "controls"}
        %button{type: "submit", value: "Signup", class: "btn btn-primary"} Create

app/views/posts/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/services/cosmetic.html.haml
%h1 Services#cosmetic
%p Find me in app/views/services/cosmetic.html.haml

app/views/services/insurance.html.haml
%h2 Insurance
%div{class: "row span12"}
  %p
    Pace Dermatology accepts the following insurance plans. If you don’t see your plan listed, please call our office at #{link_to "(253)-572-2842", "tel:(253) 572-2842"} and we can check on your individual coverage. If we are not already a participant, we may like to become one. As a courtesy to our patients, we will submit to most PPO insurance companies for reimbursement even if we are not on their list of preferred providers.

  %ul
    %li Medicare
    %li Lifewise
    %li Premera Blue Cross
    %li Labor and Industries
    %li Humana/Choice Care
    %li Regence BlueShield
    %li AARP
    %li Aetna
    %li Cigna
    %li Community Health Plan
    %li First Choice Health
    %li First Health
    %li Group Health Cooperative
    %li Medicaid
    %li Molina Healthcare
    %li Multiplan/PHCS/Beechstreet
    %li United Health Care
    %li Tricare – If Tricare is your primary coverage, an out of network referral may be required.

app/views/services/laser.html.haml
%h1 Services#laser
%p Find me in app/views/services/laser.html.haml

app/views/services/medical.html.haml
%h2 Medical Dermatology
%div{class: "row span12"}
  %p
    We provide the full spectrum of medical dermatologic care, all of which is performed by a board certified dermatologist. Below are a few of the most common skin conditions we treat. Dr. Pace has a special interest in pigmented nevi, moles, as well as skin cancer, and rashes. Please call our office at #{link_to "(253) 572-2842", "tel:(253) 572-2842"} to make an appointment or see if we are able to treat your condition.

  %ul
    %li Acne
    %li Scars
    %li Aging Skin
    %li Skin Cancers
    %li Moles
    %li Rashes
    %li Eczema
    %li Cysts
    %li Psoriasis
    %li Rosacea
    %li Shingles
    %li Warts
    %li Birthmarks
    %li Dermatitis
    %li Poison Ivy
    %li Boils
    %li Hair Infections
    %li Excessive Sweating

app/views/services/surgical.html.haml
%h1 Services#surgical
%p Find me in app/views/services/surgical.html.haml

app/views/shop/home.html.haml
%h1 Shop#home
%p Find me in app/views/shop/home.html.haml